ARG IMPORT_VERSION=v4

FROM tutorcruncher/tc-virus-checker-image:latest AS builder
RUN /render/build-scripts/apply-buildpacks.py ${HEROKU_STACK}

# For running the app, this is the base image
FROM tutorcruncher/tc-virus-checker-image:latest AS runner

# Here we copy your build artifacts from the build image to the runner so that
# the image that we deploy to Render is smaller and, therefore, can start up
# faster.
COPY --from=builder --chown=1000:1000 /render /render/
COPY --from=builder --chown=1000:1000 /app /app/

# Here we're switching to a non-root user in the container to remove some categories
# of container-escape attack.
USER 1000:1000
WORKDIR /app

# This sources all /app/.profile.d/*.sh files before process start.
# These are created by buildpacks, and you probably don't have to worry about this.
# https://devcenter.heroku.com/articles/buildpack-api#profile-d-scripts
ENTRYPOINT [ "/render/setup-env" ]

CMD [ "/render/process/web" ]
